### ISSUE TITLE
flash within windows OS

### ISSUE THREAD

**Issue by TylonHH** [sowbug/neje_laser_upgrade#1]
just wanna confirm that this prompt worked for me under a windows maschine

`c:\NEJE\cache\avrdude -u -c arduino -p m328p -P COM10 -b 58000 -U flash:w:"C:\TEMP\avrdude-v8.0-windows-x64\grbl_v1.1h.20190825.hex":a `

**Comment by sowbug** [comment]
Good to know. Thanks!

**Comment by sowbug** [comment]
Added to README in https://github.com/sowbug/neje_laser_upgrade/commit/c184d0d761e3051924caedfc6656eff257371ea6
